'use client';
import {usePullRefresh} from '@/components/PullToRefresh';
import {useEffect,useState} from 'react';
import {Admission} from '@/types';
import {DataService} from '@/lib/supabase';
import {PatientDetails} from '@/components/PatientDetails';
import {DataSkeleton,ButtonSpinner} from '@/components/LoadingFeedback';
import {Search,RefreshCw,ChevronRight,UserRound} from 'lucide-react';
export default function PatientsPage(){
 const [admissions,setAdmissions]=useState<Admission[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState('');const [query,setQuery]=useState('');const [ward,setWard]=useState('all');const [status,setStatus]=useState('active');const [selected,setSelected]=useState<string|null>(null);
 async function load(){setRefreshing(true);try{setAdmissions(await DataService.getAdmissions());setError('');}catch(e){setError(e&&typeof e==='object'&&'message'in e?String(e.message):'Unable to load patients.');}finally{setLoading(false);setRefreshing(false);}}
 usePullRefresh(load);
 useEffect(()=>{setQuery(new URLSearchParams(window.location.search).get('q')||'');load();const change=()=>{void load();};window.addEventListener('bedpulse_data_change',change);return()=>window.removeEventListener('bedpulse_data_change',change);},[]);
 const current=admissions.find(a=>a.id===selected);const wards=Array.from(new Map(admissions.filter(a=>a.ward).map(a=>[a.ward!.id,a.ward!])).values());
 const visible=admissions.filter(a=>(status==='all'||(status==='active'?['admitted','shifted'].includes(a.status):!['admitted','shifted'].includes(a.status)))&&(ward==='all'||a.ward_id===ward)&&[a.patient?.full_name,a.patient?.uhid,a.bed?.bed_number].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <><div className="space-y-5 pb-6">{loading?<DataSkeleton/>:current?<PatientDetails key={current.id} admission={current} onBack={()=>setSelected(null)} onChanged={load}/>:<><header className="flex items-center justify-between"><div><h1 className="text-3xl font-semibold tracking-tight">Patients</h1><p className="text-xs text-slate-500 mt-2">{admissions.filter(a=>['admitted','shifted'].includes(a.status)).length} currently admitted</p></div><button disabled={refreshing} onClick={load} className="flex items-center gap-2 text-xs border border-brand-100 rounded-xl p-3 bg-white">{refreshing?<ButtonSpinner/>:<RefreshCw size={15}/>}Refresh</button></header>{error&&<p role="alert" className="text-sm text-rose-700">{error}</p>}<section className="bg-white rounded-2xl border border-brand-100 p-4 grid grid-cols-2 sm:grid-cols-[1.5fr_1fr_1fr] gap-3"><label className="text-xs col-span-2 sm:col-span-1">Search<input placeholder="Patient, UHID or bed" value={query} onChange={e=>setQuery(e.target.value)} className="w-full block rounded-xl border border-brand-100 p-3 mt-2"/></label><label className="text-xs">Ward<select value={ward} onChange={e=>setWard(e.target.value)} className="w-full block rounded-xl border border-brand-100 p-3 mt-2"><option value="all">All wards</option>{wards.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label className="text-xs">Status<select value={status} onChange={e=>setStatus(e.target.value)} className="w-full block rounded-xl border border-brand-100 p-3 mt-2"><option value="active">Admitted</option><option value="discharged">Discharged / referred</option><option value="all">All patients</option></select></label></section><section className="bg-white rounded-2xl border border-brand-100 divide-y divide-brand-100">{visible.map(a=><button key={a.id} onClick={()=>setSelected(a.id)} className="w-full flex gap-3 items-center text-left p-4 hover:bg-brand-50"><span className="bg-brand-50 text-brand-600 p-3 rounded-xl"><UserRound size={19}/></span><div className="min-w-0 flex-1"><h2 className="text-sm font-semibold truncate">{a.patient?.full_name||'Patient record unavailable'}</h2><p className="text-[11px] text-slate-500 mt-1 truncate">{a.patient?.age}y · {a.patient?.gender} · {a.patient?.uhid}</p><p className="text-xs text-slate-500 mt-2">{a.admitting_doctor}</p></div><div className="text-right text-xs"><p className="font-semibold">{a.bed?.bed_number}</p><p className="text-slate-500 mt-1">{a.ward?.name}</p><p className="text-[10px] capitalize mt-2">{a.status}</p></div><ChevronRight size={16} className="shrink-0 text-brand-400"/></button>)}{!visible.length&&<p className="p-8 text-center text-sm text-slate-500">No patients match these filters.</p>}</section></>}</div></>;
}
