'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Admission,Patient} from '@/types';
import {DataService,HospitalStaff,PatientActivity} from '@/lib/supabase';
import {HospitalService} from '@/lib/hospital';
import {ButtonSpinner} from './LoadingFeedback';
import {ArrowLeft,ArrowRightLeft,LogOut,Pencil,Clock} from 'lucide-react';
export function PatientDetails({admission,onBack,onChanged}:{admission:Admission;onBack:()=>void;onChanged:()=>Promise<void>}){
 const [events,setEvents]=useState<PatientActivity[]>([]);const [staff,setStaff]=useState<HospitalStaff[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [editing,setEditing]=useState(false);const [correction,setCorrection]=useState<string|null>(null);const [performer,setPerformer]=useState('');const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [form,setForm]=useState({full_name:admission.patient?.full_name||'',age:admission.patient?.age||0,gender:admission.patient?.gender||'other',mobile:admission.patient?.mobile||''});
 async function load(){setError('');try{const [e,s]=await Promise.all([DataService.getPatientActivity(admission.patient_id),DataService.getHospitalStaff()]);setEvents(e);setStaff(s);}catch(e){setError(e&&typeof e==='object'&&'message'in e?String(e.message):'Unable to load activity.');}finally{setLoading(false);}}
 useEffect(()=>{load();},[admission.patient_id]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{if(correction)await DataService.correctActivity(correction,performer,reason);else await DataService.editPatient(admission.id,form,reason);await onChanged();await load();setEditing(false);setCorrection(null);setReason('');}catch(e){setError(e&&typeof e==='object'&&'message'in e?String(e.message):'Unable to save.');}finally{setBusy(false);}}
 const active=['admitted','shifted'].includes(admission.status);const titles:Record<string,string>={admit:'Patient admitted',shift:'Bed transfer',discharge:'Patient discharged',edit:'Patient details updated',correction:'Staff attribution corrected'};
 return <div className="space-y-5"><button onClick={onBack} className="flex gap-2 items-center text-sm text-brand-600"><ArrowLeft size={16}/>All patients</button><section className="bg-white border border-brand-100 rounded-2xl p-5"><div className="flex justify-between gap-3"><div><h1 className="text-2xl font-semibold">{admission.patient?.full_name}</h1><p className="text-xs text-slate-500 mt-2">{admission.patient?.age} years · {admission.patient?.gender} · {admission.patient?.uhid}</p></div><button onClick={()=>{setEditing(true);setCorrection(null);setReason('');}} className="flex items-center gap-1 text-xs text-brand-600"><Pencil size={14}/>Edit</button></div><div className="flex flex-wrap gap-3 mt-4 text-xs"><span className="bg-brand-50 rounded-lg px-3 py-2">{admission.ward?.name} · {admission.bed?.bed_number}</span><span className="px-3 py-2">{admission.admitting_doctor}</span><span className="px-3 py-2 capitalize">{admission.status}</span></div><p className="text-sm mt-3">{admission.provisional_diagnosis}</p>{active&&<div className="flex gap-3 mt-5"><Link href={`/transfers?admissionId=${admission.id}`} className="flex items-center gap-2 border border-brand-200 p-3 rounded-xl text-xs"><ArrowRightLeft size={15}/>Transfer</Link>{HospitalService.current()?.role!=='Nurse'&&<Link href={`/discharge?admissionId=${admission.id}`} className="flex items-center gap-2 border border-brand-200 p-3 rounded-xl text-xs"><LogOut size={15}/>Discharge</Link>}</div>}</section>
 {error&&<p role="alert" className="text-sm text-rose-700 bg-rose-50 rounded-xl p-3">{error}</p>}
 {(editing||correction)&&<form onSubmit={save} className="bg-white border border-brand-200 rounded-2xl p-5 space-y-4"><h2 className="font-semibold">{correction?'Correct performed-by staff':'Edit patient details'}</h2>{correction?<label className="block text-xs">Performed by<select required value={performer} onChange={e=>setPerformer(e.target.value)} className="block w-full p-3 mt-2 rounded-xl border border-brand-200"><option value="">Select staff</option>{staff.map(s=><option key={s.user_id} value={s.user_id}>{s.full_name} · {s.role}</option>)}</select></label>:<div className="grid sm:grid-cols-2 gap-3"><label className="text-xs">Full name<input required minLength={2} value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} className="block mt-2 w-full border border-brand-200 rounded-xl p-3"/></label><label className="text-xs">Age<input required min={0} max={130} type="number" value={form.age} onChange={e=>setForm({...form,age:Number(e.target.value)})} className="block mt-2 w-full border border-brand-200 rounded-xl p-3"/></label><label className="text-xs">Gender<select value={form.gender} onChange={e=>setForm({...form,gender:e.target.value as Patient['gender']})} className="block mt-2 w-full border border-brand-200 rounded-xl p-3"><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option></select></label><label className="text-xs">Mobile<input value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})} className="block mt-2 w-full border border-brand-200 rounded-xl p-3"/></label></div>}<label className="block text-xs">Reason for change<textarea required minLength={3} value={reason} onChange={e=>setReason(e.target.value)} className="block w-full rounded-xl border border-brand-200 p-3 mt-2"/></label><div className="flex gap-3"><button disabled={busy} className="flex items-center gap-2 bg-brand-700 text-white rounded-xl p-3 text-xs disabled:opacity-50">{busy&&<ButtonSpinner/>}{busy?'Saving…':'Save change'}</button><button type="button" disabled={busy} onClick={()=>{setEditing(false);setCorrection(null);}} className="text-xs p-3">Cancel</button></div></form>}
 <section className="bg-white border border-brand-100 rounded-2xl p-5"><h2 className="flex gap-2 items-center font-semibold"><Clock size={17}/>Activity timeline</h2>{loading?<div role="status" className="space-y-3 mt-5">{[1,2,3].map(i=><div key={i} className="skeleton h-16 rounded-xl"/>)}</div>:<ol className="mt-5 space-y-5">{events.map(event=><li key={event.id} className="border-l-2 border-brand-200 pl-4"><div className="flex justify-between gap-2"><h3 className="text-sm font-semibold">{titles[event.action]||event.action}</h3><time className="text-[10px] text-slate-500">{new Date(event.created_at).toLocaleString('en-IN',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit',timeZone:'Asia/Kolkata'})}</time></div><p className="text-xs mt-2">{event.performed_name}</p><p className="text-[11px] text-slate-500 mt-1">Recorded by {event.recorded_name}</p>{Boolean(event.details.from_bed)&&<p className="text-xs mt-2">{String(event.details.from_bed)} → {event.action==='discharge'?'Discharge':String(event.details.to_bed||'')}</p>}{event.action==='admit'&&Boolean(event.details.to_bed)&&<p className="text-xs mt-2">Bed {String(event.details.to_bed)}</p>}{event.action==='edit'&&<div className="text-xs mt-2 space-y-1">{['full_name','age','gender','mobile'].map(key=>{const before=event.details.before as Record<string,unknown>;const after=event.details.after as Record<string,unknown>;return before?.[key]!==after?.[key]?<p key={key}>{key.replace('_',' ')}: {String(before?.[key]??'')} → {String(after?.[key]??'')}</p>:null;})}</div>}{event.action==='correction'&&<p className="text-xs mt-2">{String(event.details.previous_performer)} → {event.performed_name}</p>}{Boolean(event.details.reason)&&<p className="text-xs text-slate-500 mt-2">{String(event.details.reason)}</p>}{HospitalService.current()?.role==='Admin'&&['admit','shift','discharge'].includes(event.action)&&<button onClick={()=>{setCorrection(event.id);setEditing(false);setPerformer(event.performed_by);setReason('');}} className="mt-2 text-[11px] text-brand-600 underline underline-offset-4">Correct staff attribution</button>}</li>)}</ol>}{!loading&&!events.length&&!error&&<p className="text-sm text-slate-500 mt-5">No recorded activity yet. Older actions were not attributed and will not show staff names.</p>}</section></div>;
}
