'use client';
import {useEffect,useRef,useState} from 'react';
import {usePathname} from 'next/navigation';
import {ArrowDown,RefreshCw} from 'lucide-react';
type RefreshRequest=CustomEvent<{tasks:Promise<unknown>[]}>
export function usePullRefresh(callback:()=>Promise<unknown>){const ref=useRef(callback);ref.current=callback;useEffect(()=>{const run=(event:Event)=>{(event as RefreshRequest).detail.tasks.push(Promise.resolve().then(()=>ref.current()));};window.addEventListener('bedpulse_pull_refresh',run);return()=>window.removeEventListener('bedpulse_pull_refresh',run);},[]);}
export function PullToRefresh(){const path=usePathname();const [distance,setDistance]=useState(0);const [busy,setBusy]=useState(false);const pulling=useRef(false);const amount=useRef(0);const refreshing=useRef(false);
 useEffect(()=>{let startY=0,startX=0;let container:HTMLElement|null=null;const begin=(e:TouchEvent)=>{if(refreshing.current||e.touches.length!==1||!matchMedia('(pointer: coarse)').matches)return;const target=e.target as HTMLElement;if(target.closest('input,textarea,select,button,[role="dialog"]'))return;container=target.closest('[data-pull-refresh-scroll]') as HTMLElement|null;const scrollTop=container?container.scrollTop:document.scrollingElement?.scrollTop||0;if(scrollTop>0)return;startY=e.touches[0].clientY;startX=e.touches[0].clientX;pulling.current=true;amount.current=0;};const move=(e:TouchEvent)=>{if(!pulling.current||e.touches.length!==1)return;const dy=e.touches[0].clientY-startY;const dx=e.touches[0].clientX-startX;if(dy<0||Math.abs(dx)>Math.abs(dy)){pulling.current=false;setDistance(0);return;}if(dy>10){if(e.cancelable)e.preventDefault();amount.current=Math.min(100,dy*.5);setDistance(amount.current);}};const end=async()=>{if(!pulling.current)return;pulling.current=false;if(amount.current<65){setDistance(0);return;}refreshing.current=true;setBusy(true);setDistance(60);const tasks:Promise<unknown>[]=[];window.dispatchEvent(new CustomEvent('bedpulse_pull_refresh',{detail:{tasks}}));try{if(tasks.length)await Promise.allSettled(tasks);else setDistance(0);}finally{refreshing.current=false;setBusy(false);setDistance(0);amount.current=0;}};const cancel=()=>{pulling.current=false;amount.current=0;setDistance(0);};document.addEventListener('touchstart',begin,{passive:true});document.addEventListener('touchmove',move,{passive:false});document.addEventListener('touchend',end);document.addEventListener('touchcancel',cancel);return()=>{document.removeEventListener('touchstart',begin);document.removeEventListener('touchmove',move);document.removeEventListener('touchend',end);document.removeEventListener('touchcancel',cancel);};},[path]);
 if(!distance&&!busy)return null;return <div role="status" aria-live="polite" className="fixed top-2 left-1/2 -translate-x-1/2 z-[110] bg-white border border-brand-200 rounded-full shadow-sm px-4 py-2 flex items-center gap-2 text-xs text-brand-700" style={{transform:`translate(-50%, ${Math.max(0,distance-30)}px)`}}>{busy?<RefreshCw size={16} className="animate-spin"/>:<ArrowDown size={16}/>} {busy?'Refreshing…':distance>=65?'Release to refresh':'Pull to refresh'}</div>;
}
