'use client';
import { ButtonSpinner } from '@/components/LoadingFeedback';

import React, {useState} from 'react';
import {Ward,Bed,Admission,BedStatus} from '@/types';
import {BedDouble,UserPlus,ArrowRightLeft,LogOut,Sparkles,User,Search,X,ChevronLeft,ChevronRight,Wrench} from 'lucide-react';
interface WardBedMatrixProps {wards:Ward[];beds:Bed[];admissions:Admission[];onAdmitToBed:(bed:Bed)=>void;onShiftBed:(admission:Admission)=>void;onDischargeBed:(admission:Admission)=>void;onMarkBedClean:(bedId:string)=>void}
const statusLabels:Record<BedStatus,string>={vacant:'Available',occupied:'Occupied',cleaning:'Cleaning',maintenance:'Maintenance'};
const statusStyles:Record<BedStatus,string>={vacant:'bg-[#F5FAF3] border-[#DAE8D5] text-[#52785D]',occupied:'bg-brand-50 border-brand-300 text-brand-800',cleaning:'bg-amber-50 border-amber-200 text-amber-800',maintenance:'bg-slate-50 border-slate-200 text-slate-500'};
export function WardBedMatrix({wards,beds,admissions,onAdmitToBed,onShiftBed,onDischargeBed,onMarkBedClean}:WardBedMatrixProps){
 const [wardId,setWardId]=useState('all');const [status,setStatus]=useState<BedStatus|'all'>('all');const [query,setQuery]=useState('');const [page,setPage]=useState(0);const [selectedId,setSelectedId]=useState<string|null>(null);const [cleaning,setCleaning]=useState(false);const [error,setError]=useState('');
 const admissionFor=(id:string)=>admissions.find(a=>a.bed_id===id&&(a.status==='admitted'||a.status==='shifted'));
 const filtered=beds.filter(b=>{const a=admissionFor(b.id);const ward=wards.find(w=>w.id===b.ward_id);return(wardId==='all'||b.ward_id===wardId)&&(status==='all'||b.status===status)&&[b.bed_number,a?.patient?.full_name,a?.patient?.uhid,ward?.name].filter(Boolean).join(' ').toLowerCase().includes(query.trim().toLowerCase());}).sort((a,b)=>{const aw=wards.find(w=>w.id===a.ward_id)?.name||'';const bw=wards.find(w=>w.id===b.ward_id)?.name||'';return aw.localeCompare(bw)||a.bed_number.localeCompare(b.bed_number,undefined,{numeric:true});});
 const pages=Math.ceil(filtered.length/12);const current=Math.min(page,Math.max(0,pages-1));const visible=filtered.slice(current*12,current*12+12);const selected=beds.find(b=>b.id===selectedId);const admission=selected?admissionFor(selected.id):undefined;
 function reset(){setPage(0);setSelectedId(null);setError('');}
 async function clean(){if(!selected)return;setCleaning(true);setError('');try{await onMarkBedClean(selected.id);setSelectedId(null);}catch(e){setError(e instanceof Error?e.message:'Unable to mark bed clean.');}finally{setCleaning(false);}}
 return <section id="ward-grid-section" className="bg-white rounded-2xl border border-brand-100 p-4 sm:p-5 space-y-4">
  <header className="flex items-center justify-between gap-3"><h2 className="text-base font-semibold flex items-center gap-2"><BedDouble size={19} className="text-brand-500"/>Ward & bed overview</h2><span className="text-xs text-slate-500">{filtered.length} beds</span></header>
  <div className="grid grid-cols-2 sm:grid-cols-[1fr_1fr_1.4fr] gap-2"><label className="text-xs text-slate-500">Ward<select aria-label="Filter by ward" value={wardId} onChange={e=>{setWardId(e.target.value);reset();}} className="mt-1 w-full rounded-xl border border-brand-100 bg-[#F8FAF9] p-2.5 text-xs text-brand-800"><option value="all">All wards</option>{wards.map(w=><option key={w.id} value={w.id}>{w.name} ({beds.filter(b=>b.ward_id===w.id).length})</option>)}</select></label><label className="text-xs text-slate-500">Status<select aria-label="Filter by bed status" value={status} onChange={e=>{setStatus(e.target.value as BedStatus|'all');reset();}} className="mt-1 w-full rounded-xl border border-brand-100 bg-[#F8FAF9] p-2.5 text-xs text-brand-800"><option value="all">All statuses</option>{Object.entries(statusLabels).map(([s,label])=><option key={s} value={s}>{label}</option>)}</select></label><label className="col-span-2 sm:col-span-1 text-xs text-slate-500">Search<div className="relative mt-1"><Search size={14} className="absolute left-3 top-3 text-slate-400"/><input aria-label="Search beds or patients" placeholder="Bed, patient or UHID" value={query} onChange={e=>{setQuery(e.target.value);reset();}} className="w-full rounded-xl border border-brand-100 bg-[#F8FAF9] py-2.5 pl-9 pr-3 text-xs text-brand-800"/></div></label></div>
  {(wardId!=='all'||status!=='all'||query)&&<button onClick={()=>{setWardId('all');setStatus('all');setQuery('');reset();}} className="text-xs text-brand-600 underline underline-offset-4">Clear filters</button>}
  <div className="space-y-4">{wards.filter(w=>visible.some(b=>b.ward_id===w.id)).map(w=><div key={w.id}><h3 className="mb-2 text-xs font-semibold text-slate-500">{w.name}</h3><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-2">{visible.filter(b=>b.ward_id===w.id).map(b=>{const a=admissionFor(b.id);const Icon=b.status==='occupied'?User:b.status==='cleaning'?Sparkles:b.status==='maintenance'?Wrench:BedDouble;return <button key={b.id} onClick={()=>{setSelectedId(b.id);setError('');}} aria-pressed={b.id===selectedId} aria-label={`${b.bed_number}, ${statusLabels[b.status]}${a?.patient?.full_name?', '+a.patient.full_name:''}`} className={`min-h-[88px] rounded-xl border p-3 text-left transition hover:brightness-95 ${statusStyles[b.status]} ${selectedId===b.id?'ring-2 ring-brand-400 ring-offset-1':''}`}><div className="flex justify-between gap-1"><span className="text-xs font-semibold truncate">{b.bed_number}</span><Icon size={16} className="shrink-0"/></div><p className="text-[10px] mt-2">{statusLabels[b.status]}</p>{a?.patient?.full_name&&<p className="text-[10px] truncate mt-1" title={a.patient.full_name}>{a.patient.full_name}</p>}</button>;})}</div></div>)}</div>
  {filtered.length===0&&<div className="text-center py-8 text-sm text-slate-500">{beds.length?'No beds match these filters.':'No beds added yet.'}</div>}
  {selected&&<section aria-label="Selected bed details" className="border border-brand-200 bg-[#F8FAF9] rounded-xl p-4 space-y-3"><div className="flex justify-between items-start gap-2"><div><h3 className="text-sm font-semibold">{selected.bed_number} · {statusLabels[selected.status]}</h3><p className="text-xs text-slate-500 mt-1">{wards.find(w=>w.id===selected.ward_id)?.name} · {selected.room_type||selected.bed_type||'Standard'}</p></div><button onClick={()=>setSelectedId(null)} aria-label="Close bed details" className="p-1"><X size={18}/></button></div>{admission&&<div className="text-xs space-y-1"><p className="font-semibold">{admission.patient?.full_name||'Patient record unavailable'}</p>{admission.patient?.uhid&&<p className="text-slate-500">{admission.patient.uhid}</p>}<p>{admission.provisional_diagnosis}</p><p className="text-slate-500">{admission.admitting_doctor}</p></div>}{error&&<p role="alert" className="text-xs text-rose-700">{error}</p>}<div className="flex flex-wrap gap-2">{selected.status==='vacant'&&<button onClick={()=>onAdmitToBed(selected)} className="flex gap-2 items-center bg-brand-700 text-white px-4 py-2.5 rounded-xl text-xs font-semibold"><UserPlus size={15}/>Admit patient</button>}{selected.status==='occupied'&&<><button disabled={!admission} onClick={()=>admission&&onShiftBed(admission)} className="flex gap-2 items-center border border-brand-200 bg-white px-4 py-2.5 rounded-xl text-xs font-semibold disabled:opacity-40"><ArrowRightLeft size={15}/>Transfer</button><button disabled={!admission} onClick={()=>admission&&onDischargeBed(admission)} className="flex gap-2 items-center border border-brand-200 bg-white px-4 py-2.5 rounded-xl text-xs font-semibold disabled:opacity-40"><LogOut size={15}/>Discharge</button></>}{selected.status==='cleaning'&&<button disabled={cleaning} onClick={clean} className="flex gap-2 items-center bg-brand-700 text-white px-4 py-2.5 rounded-xl text-xs font-semibold disabled:opacity-50">{cleaning && <ButtonSpinner />}<Sparkles size={15}/>{cleaning?'Saving…':'Mark clean'}</button>}{selected.status==='maintenance'&&<p className="text-xs text-slate-500">Unavailable while under maintenance.</p>}</div></section>}
  {pages>1&&<footer className="flex items-center justify-between border-t border-brand-100 pt-3"><span className="text-xs text-slate-500">{current*12+1}–{Math.min(current*12+12,filtered.length)} of {filtered.length}</span><div className="flex items-center gap-2"><button aria-label="Previous beds" disabled={current===0} onClick={()=>{setPage(current-1);setSelectedId(null);}} className="p-2 border border-brand-100 rounded-lg disabled:opacity-30"><ChevronLeft size={16}/></button><span className="text-xs">{current+1} / {pages}</span><button aria-label="Next beds" disabled={current>=pages-1} onClick={()=>{setPage(current+1);setSelectedId(null);}} className="p-2 border border-brand-100 rounded-lg disabled:opacity-30"><ChevronRight size={16}/></button></div></footer>}
 </section>;
}
