'use client';
import {usePullRefresh} from '@/components/PullToRefresh';
import { startNavigation, ButtonSpinner } from '@/components/LoadingFeedback';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { createClient } from '@/utils/supabase/client';
import { HospitalService, HospitalMembership } from '@/lib/hospital';
export default function SetupPage() {
 const router=useRouter(); const [membership,setMembership]=useState<HospitalMembership|null>(null); const [ready,setReady]=useState(false); const [name,setName]=useState(''); const [code,setCode]=useState(''); const [ward,setWard]=useState(''); const [wardCode,setWardCode]=useState(''); const [bed,setBed]=useState(''); const [wardId,setWardId]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
 async function load(){ const {data:isAdmin,error:adminError}=await createClient().rpc('is_platform_admin'); if(adminError)throw new Error(adminError.message); if(isAdmin===true){(startNavigation(), router.replace)('/super-admin');return;} const m=await HospitalService.resolve(); setMembership(m); if(m?.hospital.setup_completed) {(startNavigation(), router.replace)('/dashboard');return;} if(m) {const {data,error}=await createClient().from('wards').select('id').eq('hospital_id',m.hospital_id).order('created_at').limit(1).maybeSingle();if(error)throw error;setWardId(data?.id||'');}setReady(true); }
 usePullRefresh(load);
 useEffect(()=>{load().catch(e=>{setMessage(e.message);setReady(true);});},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const c=createClient();if(!membership){const {error}=await c.rpc('create_hospital',{details:{name,code}});if(error)throw error;await load();}else if(!wardId){const {data,error}=await c.from('wards').insert({hospital_id:membership.hospital_id,name:ward,code:wardCode,color_accent:'#789986'}).select('id').single();if(error)throw error;setWardId(data.id);}else{const {error}=await c.from('beds').insert({hospital_id:membership.hospital_id,ward_id:wardId,bed_number:bed,status:'vacant',room_type:'Standard',daily_rate:0});if(error)throw error;const {error:completion}=await c.rpc('complete_hospital_setup',{hospital:membership.hospital_id});if(completion)throw completion;await load();}}catch(e){setMessage(e instanceof Error?e.message:'Setup failed.');}finally{setBusy(false);}}
 return <main className="min-h-screen bg-[#F8FAF9] flex items-center justify-center p-6"><section className="max-w-lg w-full rounded-3xl border border-brand-100 bg-white p-8"><Link href="/" className="text-brand-700 font-semibold">BedPulse</Link><h1 className="text-2xl font-semibold mt-6">{membership?.hospital.name || 'Set up your hospital'}</h1><p className="text-sm text-slate-500 mt-2 mb-6">Complete setup to start patient management.</p>{message&&<p role="alert" className="text-sm text-rose-700 mb-4">{message}</p>}{!ready?<p>Checking your account…</p>:membership&&membership.role!=='Admin'?<p className="text-sm">Your hospital administrator needs to complete setup.</p>:<form onSubmit={submit} className="space-y-4">{(!membership?[{label:'Hospital name',value:name,set:setName},{label:'Hospital code',value:code,set:setCode}]:!wardId?[{label:'First ward name',value:ward,set:setWard},{label:'Ward code',value:wardCode,set:setWardCode}]:[{label:'First bed number',value:bed,set:setBed}]).map(field=><label key={field.label} className="block text-sm font-medium">{field.label}<input required value={field.value} onChange={e=>field.set(e.target.value)} className="block mt-2 w-full rounded-xl border border-brand-200 p-3" /></label>)}<button disabled={busy} className="bg-brand-700 text-white rounded-xl px-5 py-3 text-sm disabled:opacity-50">{busy && <ButtonSpinner />}{busy?'Saving…':!membership?'Create hospital':!wardId?'Add ward':'Add bed & complete setup'}</button></form>}</section></main>;
}
